Repository ntut-open-source-club/practical-tools-for-simple-design, pull requests merged in 2023-07, with the labels that each got.

#21 Fix OpenGL platform-specific problem
  include/Core/DebugMessageCallback.hpp
  src/Core/DebugMessageCallback.cpp
Labels: bug, Windows

#25 Remove `SDL2main` from `Tests`
  CMakeLists.txt
  cmake/Dependencies.cmake
Labels: bug, Windows

#26 Misc refactor & Separate `AudioTest`
  CMakeLists.txt
  test/Interactive/Audio.cpp
Labels: refactoring, automation

#28 Meet #11 's requirement
  include/Util/BGM.hpp
  include/Util/SFX.hpp
Labels: documentation
