Repository ntut-open-source-club/practical-tools-for-simple-design, pull requests merged in 2024-04, with the labels that each got.

#113 Add a pivot for GameObject
  include/Core/Drawable.hpp
  include/Util/Animation.hpp
  include/Util/GameObject.hpp
  include/Util/Image.hpp
  include/Util/Text.hpp
  src/Util/Animation.cpp
  src/Util/GameObject.cpp
  src/Util/Image.cpp
  src/Util/Text.cpp
  src/Util/TransformUtils.cpp
Labels: enhancement

#173 Set the window icon with sdl2
  .gitignore
  CMakeLists.txt
  assets/icon.jpg
  example/src/main.cpp
  include/Core/Context.hpp
  src/Core/Context.cpp
Labels: enhancement

#180 check if m_Drawable is nullptr
  src/Util/GameObject.cpp
Labels: bug

#182 Fix Delta time & Delay
  .clang-format
  example/src/Giraffe.cpp
  example/src/GiraffeText.cpp
  include/Core/Context.hpp
  include/Util/Time.hpp
  src/Core/Context.cpp
  src/Util/Animation.cpp
  src/Util/Time.cpp
Labels: bug, refactoring
