Repository ntut-open-source-club/practical-tools-for-simple-design, pull requests merged in 2024-01, with the labels that each got.

#50 added clang-format and clang-tidy workflow checks
  .clang-tidy
  .github/workflows/build.yml
  src/App.cpp
  src/Giraffe.cpp
Labels: automation

#82 📝 Code Styles and Guidelines
  .github/docs/Code-Styles-and-Guidelines.md
  CONTRIBUTING.md
Labels: documentation

#84 Add auto tree rendering root
  CMakeLists.txt
  include/App.hpp
  include/Triangle.hpp
  include/Util/GameObject.hpp
  include/Util/Root.hpp
  src/App.cpp
  src/Giraffe.cpp
  src/Triangle.cpp
  src/Util/GameObject.cpp
  src/Util/Root.cpp
Labels: enhancement
