Repository ntut-open-source-club/practical-tools-for-simple-design, pull requests merged in 2024-05, with the labels that each got.

#174 Runtime config
  CMakeLists.txt
  cmake/Dependencies.cmake
  example/src/Giraffe.cpp
  include/Core/Context.hpp
  include/config.hpp
  include/pch.hpp
  src/Core/Context.cpp
  src/Util/Input.cpp
  src/Util/Logger.cpp
  src/Util/Text.cpp
  src/Util/TransformUtils.cpp
  src/config.cpp
Labels: enhancement, breaking

#175 Typed Coordinate Convention
  CMakeLists.txt
  example/src/App.cpp
  include/Util/Input.hpp
  include/Util/Position.hpp
  include/Util/Position.inl
  src/Util/Input.cpp
  src/Util/Position.cpp
  test/PositionTest.cpp
Labels: refactoring

#189 Bug-fix: Fix #187
  include/config.hpp
  src/Core/Context.cpp
  src/config.cpp
Labels: bug
