Repository ntut-open-source-club/practical-tools-for-simple-design, pull requests merged in 2024-02, with the labels that each got.

#85 add size to image
  include/Core/Drawable.hpp
  include/Util/GameObject.hpp
  include/Util/Image.hpp
  include/Util/Text.hpp
  include/Util/TransformUtils.hpp
  src/Util/Image.cpp
  src/Util/Text.cpp
  src/Util/TransformUtils.cpp
Labels: enhancement

#90 Add and fix Util doc
  .clang-format
  include/Util/BGM.hpp
  include/Util/Color.hpp
  include/Util/GameObject.hpp
  include/Util/Image.hpp
  include/Util/Input.hpp
  include/Util/Logger.hpp
  include/Util/Root.hpp
  include/Util/SFX.hpp
  include/Util/Text.hpp
  include/Util/Time.hpp
  include/Util/Transform.hpp
  include/Util/TransformUtils.hpp
Labels: documentation

#98 Update game object and adapt Util::Root
  include/App.hpp
  include/Giraffe.hpp
  include/GiraffeText.hpp
  include/Util/GameObject.hpp
  include/Util/Root.hpp
  src/App.cpp
  src/Core/DebugMessageCallback.cpp
  src/Giraffe.cpp
  src/GiraffeText.cpp
  src/Util/Input.cpp
  src/Util/Root.cpp
  src/Util/Time.cpp
Labels: enhancement

#109 added docs github actions
  .github/workflows/docs.yml
Labels: documentation, automation

#103 Enhance: Make Util::Input detect if mouse button up.
  include/Util/Input.hpp
  src/App.cpp
  src/Util/Input.cpp
Labels: enhancement

#104 📝 Add bug report template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation

#121 z-index sort
  src/Util/Root.cpp
Labels: bug

#123 Edge detections for mouse button and key inputs.
  include/Util/Input.hpp
  include/Util/Keycode.hpp
  src/App.cpp
  src/Util/Input.cpp
Labels: enhancement

#99 Update README
  README.md
  docs/Doxyfile
Labels: documentation

#125 Doc: Add CLionQuickStart.md and related-images
  .github/docs/CLionQuickStart/CLionQuickStart.md
  .github/docs/CLionQuickStart/CMake_config.png
  .github/docs/CLionQuickStart/GH_list.png
  .github/docs/CLionQuickStart/VCS_menu.png
  .github/docs/CLionQuickStart/build.png
  .github/docs/CLionQuickStart/debug.png
  .github/docs/CLionQuickStart/img.png
  .github/docs/CLionQuickStart/mainUI.png
  .github/docs/CLionQuickStart/project_menu.png
  .github/docs/CLionQuickStart/run.png
  README.md
Labels: documentation

#127 Fix `.github/docs` can't access from doxygen page
  docs/Doxyfile
Labels: documentation

#108 Animation
  CMakeLists.txt
  assets/sprites/cat/cat-0.bmp
  assets/sprites/cat/cat-1.bmp
  assets/sprites/cat/cat-2.bmp
  assets/sprites/cat/cat-3.bmp
  assets/sprites/cat/cat-4.bmp
  assets/sprites/cat/cat-5.bmp
  assets/sprites/cat/cat-6.bmp
  assets/sprites/cat/cat-7.bmp
  include/App.hpp
  include/Cat.hpp
  include/Util/Animation.hpp
  include/Util/GameObject.hpp
  include/Util/Time.hpp
  include/config.hpp
  src/App.cpp
  src/Cat.cpp
  src/Core/Context.cpp
  src/Util/Animation.cpp
  src/Util/Time.cpp
Labels: enhancement

#129 Submodulize and library-ize PTSD
  CMakeLists.txt
  README.md
  cmake/Dependencies.cmake
  include/App.hpp
  include/Cat.hpp
  include/Giraffe.hpp
  include/GiraffeText.hpp
  src/App.cpp
  src/Cat.cpp
  src/Giraffe.cpp
  src/GiraffeText.cpp
  src/Util/Image.cpp
  src/Util/Text.cpp
  src/main.cpp
  test/Interactive/Audio.cpp
  test/NotSimpleTest.cpp
  test/SimpleTest.cpp
  test/TransformTest.cpp
Labels: enhancement

#122 fix workflow condition
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/post.yml
  assets/shaders/Base.vert
  include/Util/Input.hpp
  include/pch.hpp
  src/App.cpp
  test/Interactive/Audio.cpp
  test/TransformTest.cpp
Labels: bug, automation

#130 Try to Rewrite Animation
  include/Util/Animation.hpp
  src/Cat.cpp
  src/Util/Animation.cpp
Labels: refactoring

#73 Complete "Missing Textures Texture"
  CMakeLists.txt
  include/Core/MissingTextureBase64.hpp
  include/Util/Base64.hpp
  include/Util/MissingTexture.hpp
  src/Util/Image.cpp
  src/Util/MissingTexture.cpp
Labels: enhancement

#140 Macintosh support
  .github/workflows/build.yml
Labels: automation

#139 added format for glm::*
  include/Util/Logger.hpp
Labels: enhancement

#141 Misc jobs
  CMakeLists.txt
  include/App.hpp
  include/Util/GameObject.hpp
  include/Util/Renderer.hpp
  src/Util/Renderer.cpp
Labels: bug, documentation

#142 Update submoduleized PTSD
  CMakeLists.txt
  README.md
  assets/audio/Click.wav
  assets/audio/testbgm.mp3
  assets/fonts/Inter.ttf
  assets/sprites/cat/cat-0.bmp
  assets/sprites/cat/cat-1.bmp
  assets/sprites/cat/cat-2.bmp
  assets/sprites/cat/cat-3.bmp
  assets/sprites/cat/cat-4.bmp
  assets/sprites/cat/cat-5.bmp
  assets/sprites/cat/cat-6.bmp
  assets/sprites/cat/cat-7.bmp
  assets/sprites/giraffe.png
  cmake/Dependencies.cmake
  include/App.hpp
  include/Cat.hpp
  include/Giraffe.hpp
  include/GiraffeText.hpp
  src/App.cpp
  src/Cat.cpp
  src/Giraffe.cpp
  src/GiraffeText.cpp
  src/Util/Image.cpp
  src/Util/Text.cpp
  src/main.cpp
  test/Interactive/Audio.cpp
  test/NotSimpleTest.cpp
  test/SimpleTest.cpp
  test/TransformTest.cpp
Labels: bug, enhancement, refactoring
